### ISSUE TITLE
Clean up labels on axis

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/analytics-table#2] opened 2018-12-16 01:39 UTC
Too much label overlap at https://analytics.vipulnaik.com/?start_date=2017-01-01&end_date=2017-12-31

<img width="793" alt="screen shot 2018-12-15 at 5 39 06 pm" src="https://user-images.githubusercontent.com/7758551/50049043-569e0d00-0090-11e9-9ede-a8623a08d349.png">

@riceissa sez: "i think the standard solution is to rotate the labels a bit"

**Comment by riceissa** [comment] 2019-10-25 20:39
On my local machine, the labels look fine, probably because I am using a newer version of matplotlib:

![download](https://user-images.githubusercontent.com/1450515/67602913-83996280-f72c-11e9-9a81-8db92086fd0d.png)

I added a 45 degree rotation. I'm not sure if this will fix it (you might need to tweak the rotation) because I haven't reproduced the issue locally. If the rotation doesn't work, I can download your version of matplotlib and try to reproduce the error.

**Comment by riceissa** [comment] 2019-10-27 02:54
It looks fine to me now, so I'm closing this.

**Closed as completed by riceissa** 2019-10-27 02:54 UTC
